#!/usr/bin/env bash

# cd -P -- "${0%/*}" || exit
tee /dev/stderr | /nix/store/anp2vynvzf6pzzilcbdcsx26796qglpz-asciidoctor-2.0.18/bin/asciidoctor -r ../../lib/asciidoctor-hugo-chroma.rb --trace "$@" | tee /dev/stderr